name: Data Pipeline Workflow

on:
  push:
    branches:
      - data_pipeline
  pull_request:
    branches:
      - data_pipeline

jobs:
  setup_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Docker installation
        run: docker --version

      - name: Enable Docker BuildKit
        run: |
          echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

  build_and_push_image:
    needs: setup_environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        working-directory: mlops-crash-course-code/data_pipeline/deployment
        run: |
          DOCKER_BUILDKIT=1 docker buildx build \
            --platform linux/amd64 \
            --tag duynope1803/data-pipeline:latest \
            --push \
            -f Dockerfile .

  deploy_training_pipeline:
    needs: build_and_push_image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy training pipeline
        working-directory: training_pipeline
        env:
          AIRFLOW_HOME: /path/to/airflow
          DAG_DIR: /path/to/dags
        run: |
          make deploy_dags