name: Data Pipeline Workflow

on:
  push:
    branches:
      - main
      - data_pipeline
  pull_request:
    branches:
      - main
      - data_pipeline

jobs:
  setup_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Enable Docker BuildKit
        run: |
          echo '{"experimental": true, "features": {"buildkit": true}}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


    build_data_pipeline:
      needs: setup_environment
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build data pipeline
          working-directory: data_pipeline/deployment  # Chỉ định thư mục chứa Dockerfile
          run: |
            echo "Building data pipeline.."
            docker build -t duynope1803/data-pipeline:latest .  # Dockerfile sẽ được tìm thấy trong thư mục này

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: duynope1803  # Sử dụng tên đăng nhập Docker Hub của bạn
            password: ${{ secrets.DOCKER_PASSWORD }}  # Lấy token từ GitHub Secrets

        - name: Build and push Docker image to Docker Hub
          run: |
            docker build -t duynope1803/data-pipeline:latest .
            docker push duynope1803/data-pipeline:latest



  test_data_pipeline:
    needs: setup_environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test data pipeline
        run: |
          echo "Testing data pipeline.."

  deploy_data_pipeline:
    needs: setup_environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy data pipeline
        working-directory: data_pipeline
        run: |
          make deploy_dags
  build_training_pipeline:
    needs: setup_environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build training pipeline
        working-directory: training_pipeline
        run: |
          make build_image
  deploy_training_pipeline:
    needs: setup_environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy training pipeline
        working-directory: training_pipeline
        run: |
          make deploy_dags