name: Data Pipeline Workflow

# Sự kiện kích hoạt workflow khi có push hoặc pull request vào branch chính
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_data_pipeline:
    # Chạy job trên môi trường Ubuntu với Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build data pipeline
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        working-directory: data_pipeline
        run: |
          echo "Building data pipeline.."
          make build_image

  test_data_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Test data pipeline
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          echo "Testing data pipeline.."
          # Bạn có thể thêm lệnh test tại đây, ví dụ `make test` nếu có

  deploy_data_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Deploy data pipeline
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        working-directory: data_pipeline
        run: |
          make deploy_dags
